title: "0xaskar"
email: "askr10.askr@gmail.com"
description: "Penetration Tester | CTF Player | Cybersecurity enthusiast with a strong interest in web security and ethical hacking <3."
url: "https://abdelruhmanaskar.github.io"
github_username: "AbdelruhmanAskar"
minimal_mistakes_skin: "dark"
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
repository: "AbdelruhmanAskar/0xaskar.github.io"

permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: "Africa/Cairo"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name    : "0xaskar"
  avatar  : "https://github.com/AbdelruhmanAskar.png"
  bio     : "Penetration Tester | CTF Player"
  links:
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@0xAskar"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abdelrahmanaskar10/"
    - label: "TryHackMe"
      icon: "fas fa-fw fa-terminal"
      url: "https://tryhackme.com/p/0xaskar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AbdelruhmanAskar"

footer:
  links:
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@0xAskar"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abdelrahmanaskar10/"
    - label: "TryHackMe"
      icon: "fas fa-fw fa-terminal"
      url: "https://tryhackme.com/p/0xaskar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AbdelruhmanAskar"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
